# Generated by Django 6.1 on 2026-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_weightrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='weightrecord',
            constraint=models.UniqueConstraint(fields=('athlete', 'date'), name='unique_athlete_weight_date'),
        ),
    ]
