# Generated by Django 6.1 on 2026-08-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_athleteprofile_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAthleteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='accounts.athleteprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='accounts.coachprofile')),
            ],
            options={
                'unique_together': {('coach', 'athlete')},
            },
        ),
    ]
