# Generated by Django 6.1 on 2026-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('target_muscle', models.CharField(blank=True, max_length=100)),
                ('muscle_group', models.CharField(blank=True, max_length=100)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('gif_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
