# Generated by Django 6.1 on 2026-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='external_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction_steps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='media_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
