# Generated by Django 6.1 on 2026-08-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutsession_workoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLogSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutlog')),
            ],
        ),
    ]
