# Generated by Django 6.1 on 2026-08-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutlogset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-started_at']},
        ),
    ]
