# Generated by Django 6.1 on 2026-08-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workoutsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at']},
        ),
    ]
